language: python
services:
- postgresql
- elasticsearch
python:
- 2.7
install:
- pip install -r testing/requirements.txt
- pip install psycopg2
before_script:
- sleep 10
- cp testing/travis.local.py testing/local.py
script:
- python runtests.py
